# Generated by Django 4.1.6 on 2023-02-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regmodel',
            old_name='number',
            new_name='phone',
        ),
    ]
