# Generated by Django 4.1.6 on 2023-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_number_regmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
