# Generated by Django 4.1.5 on 2023-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_regmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
                ('imgfile', models.ImageField(upload_to='newapp/static')),
            ],
        ),
        migrations.CreateModel(
            name='sregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
