# Generated by Django 4.1.6 on 2023-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=40)),
                ('prize', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('imgfile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=40)),
                ('prize', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('imgfile', models.ImageField(upload_to='')),
            ],
        ),
    ]
