# Generated by Django 4.1.6 on 2023-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_cart_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='prize',
            new_name='price',
        ),
    ]
