# Generated by Django 4.1.5 on 2023-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_cart_description_alter_imgmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='imgname',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='imgname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='imgname',
            field=models.CharField(max_length=400),
        ),
    ]
