# Generated by Django 4.1.5 on 2023-02-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_alter_cart_imgname_alter_imgmodel_imgname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=600)),
                ('imgfile', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customercard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('cardexpiry', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=30)),
            ],
        ),
    ]
