# Generated by Django 4.1.5 on 2023-02-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_remove_buy_imgfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='price',
            new_name='prize',
        ),
    ]
