# Generated by Django 4.1.5 on 2023-02-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_rename_prize_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='imgname',
            new_name='name',
        ),
    ]
