# Generated by Django 4.1.5 on 2023-02-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_rename_imgname_buy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='name',
            new_name='imgname',
        ),
    ]
