# Generated by Django 4.1.5 on 2023-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_rename_name_buy_imgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
